# Generated by Django 6.0.4 on 2026-04-22 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DimAgeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_range', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DimChestPainType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cp_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DimGender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DimRestECG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecg_result', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PatientFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('trestbps', models.FloatField(blank=True, null=True)),
                ('chol', models.FloatField(blank=True, null=True)),
                ('fbs', models.BooleanField(default=False)),
                ('thalach', models.FloatField(blank=True, null=True)),
                ('exang', models.BooleanField(default=False)),
                ('oldpeak', models.FloatField(blank=True, null=True)),
                ('slope', models.IntegerField(blank=True, null=True)),
                ('ca', models.IntegerField(blank=True, null=True)),
                ('thal', models.IntegerField(blank=True, null=True)),
                ('target', models.BooleanField(default=False)),
                ('age_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etl.dimagegroup')),
                ('cp_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etl.dimchestpaintype')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etl.dimgender')),
                ('rest_ecg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etl.dimrestecg')),
            ],
        ),
    ]
