# Generated by Django 6.1.1 on 2026-09-03 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DimBPCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30, unique=True)),
                ('min_value', models.FloatField(default=0)),
                ('max_value', models.FloatField(default=9999)),
            ],
            options={
                'verbose_name': 'Dimension: BP Category',
                'verbose_name_plural': 'Dimension: BP Categories',
            },
        ),
        migrations.CreateModel(
            name='DimCholesterolCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30, unique=True)),
                ('min_value', models.FloatField(default=0)),
                ('max_value', models.FloatField(default=9999)),
            ],
            options={
                'verbose_name': 'Dimension: Cholesterol Category',
                'verbose_name_plural': 'Dimension: Cholesterol Categories',
            },
        ),
        migrations.CreateModel(
            name='DimHeartRateCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30, unique=True)),
                ('min_value', models.FloatField(default=0)),
                ('max_value', models.FloatField(default=9999)),
            ],
            options={
                'verbose_name': 'Dimension: Heart Rate Category',
                'verbose_name_plural': 'Dimension: Heart Rate Categories',
            },
        ),
        migrations.CreateModel(
            name='ETLLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(max_length=50, unique=True)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('RUNNING', 'Running')], default='RUNNING', max_length=10)),
                ('records_extracted', models.IntegerField(default=0)),
                ('records_validated', models.IntegerField(default=0)),
                ('records_invalid', models.IntegerField(default=0)),
                ('duplicates_detected', models.IntegerField(default=0)),
                ('records_transformed', models.IntegerField(default=0)),
                ('records_loaded', models.IntegerField(default=0)),
                ('missing_values_handled', models.IntegerField(default=0)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('data_quality_report', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'ETL Execution Log',
                'verbose_name_plural': 'ETL Execution Logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='dimagegroup',
            options={'ordering': ['min_age'], 'verbose_name': 'Dimension: Age Group', 'verbose_name_plural': 'Dimension: Age Groups'},
        ),
        migrations.AlterModelOptions(
            name='dimchestpaintype',
            options={'verbose_name': 'Dimension: Chest Pain Type', 'verbose_name_plural': 'Dimension: Chest Pain Types'},
        ),
        migrations.AlterModelOptions(
            name='dimgender',
            options={'verbose_name': 'Dimension: Gender', 'verbose_name_plural': 'Dimension: Genders'},
        ),
        migrations.AlterModelOptions(
            name='dimrestecg',
            options={'verbose_name': 'Dimension: Resting ECG', 'verbose_name_plural': 'Dimension: Resting ECGs'},
        ),
        migrations.AlterModelOptions(
            name='patientfact',
            options={'verbose_name': 'Fact: Patient Health', 'verbose_name_plural': 'Fact: Patient Health Records'},
        ),
        migrations.AddField(
            model_name='dimagegroup',
            name='max_age',
            field=models.IntegerField(default=999),
        ),
        migrations.AddField(
            model_name='dimagegroup',
            name='min_age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dimchestpaintype',
            name='cp_code',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AddField(
            model_name='dimrestecg',
            name='ecg_code',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AddField(
            model_name='patientfact',
            name='etl_batch_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='dimagegroup',
            name='age_range',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='dimgender',
            name='gender_name',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='patientfact',
            name='bp_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='etl.dimbpcategory'),
        ),
        migrations.AddField(
            model_name='patientfact',
            name='chol_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='etl.dimcholesterolcategory'),
        ),
        migrations.AddField(
            model_name='patientfact',
            name='hr_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='etl.dimheartratecategory'),
        ),
        migrations.CreateModel(
            name='DimTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etl_date', models.DateField()),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('quarter', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Dimension: Time',
                'verbose_name_plural': 'Dimension: Time',
                'unique_together': {('etl_date',)},
            },
        ),
        migrations.AddField(
            model_name='patientfact',
            name='etl_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='etl.dimtime'),
        ),
    ]
